### ISSUE TITLE
Can you change the params activity by context?

### ISSUE THREAD

**Issue by juanlabrador** [mumayank/AirLocation#12]
For this used in many places.

Thanks for create this lib

**Comment by juanlabrador** [comment]
I want to use in a Service class

**Comment by mumayank** [comment]
Since the location permission is categorized as dangerous permission by Android, the user of the app can at any time revoke it from the app settings. If we as a developer assume that the location permission will be present when requesting the location from background service, we could be wrong.

Having said that, your point still makes sense for the cases wherein the background service the developer proceeds to gain the current user location information only if the required permissions are present. In that case, the context would be better than the activity.

**Comment by mumayank** [comment]
I will try to work on it in the coming days, but since I also have a full-time job, it might not be possible to provide an estimate right now. I request you to kindly fork the repo, and if possible, make this change for your use-case for the time being. Once the library is updated by me, you can increment the lib version in the gradle.

**Comment by mumayank** [comment]
Hi @juanlabrador, Greetings. As you may be aware, Android's location access is now categorized as foreground or background. If an app requires location access in the background, the app must adhere to the location policy: https://support.google.com/googleplay/android-developer/answer/9799150. However, if the app needs access in the foreground, it can do so in 2 ways: (1) activity that belongs to your app is visible, or, (2) the app is running a foreground service.

Handling these special cases is currently beyond the general usage of the library. Hence, I've decided that the feature request is out of scope for now. The project is open-source, and please feel free to use the code in implementing your use-case. I would also love to accept a pull request, if you would be interested in that. Thanks!
