### ISSUE TITLE
Does this library work with huawei/xiaomi devices with aggresive OEM's?

### ISSUE THREAD

**Issue by cilvet** [mumayank/AirLocation#15]
I've had a lot of trouble implementing continuous location tracking for a fitness app with the suggested methods, since some phones have very aggresive battery-saving systems that kill even foreground services and stop services from getting location updates. 

Does this librar y solve the problem? sorry for asking here, I don't know where I'm supposed to ask this

**Comment by mumayank** [comment]
Hey, please, you can ask questions here :)

The library can be considered a wrapper that encapsulates a lot of repetitive tasks for the developer so that it is very easy to integrate fetching of live location feature in the app. Also, when used in multiple places, this library provides a clean, very less code to integrate the feature.

I have tested the library and it works, but then, implementing the location feature from Google Play Location Services directly was also working on those phones. If that is not working on a phone, then ideally speaking, this library should also not work, as it does nothing extra.

Could you enlist the phones you mentioned here so that if I get a chance, I could test on those? Also, if you still have access to them, would you help me running the dummy project (given in the lib repo) on them, please?
