### ISSUE TITLE
Is there any function to stop receiving updates like airLocation.stop() ?

### ISSUE THREAD

**Issue by irfnyas** [mumayank/AirLocation#16]

**Comment by vevek** [comment]
You can call for AirLocation each time you want to receive a location update, and set the callback "isLocationRequiredOnlyOneTime" to true.

**Comment by vevek** [comment]
Alternatively you can call airLocation?.stopLocationUpdates().

**Comment by ifnyas** [comment]
> Alternatively you can call airLocation?.stopLocationUpdates().

Ah I see, thanks

**Comment by irfnyas** [comment]
I'm sorry to reopened this, but I get unresolved reference when typing `airLocation?.stopLocationUpdates()`

**Comment by vevek** [comment]
It might have been renamed. But there should be a similar function.

**Comment by mumayank** [comment]
Hello guys, OP here. Sorry for the delayed response. As @vevek said, the library used to have a `stopLocationUpdates()` function earlier, but I had to remove it in later releases. It was removed because there were instances where the library wasn't working as expected like orientation change inside a fragment. I plan on bringing the feature back in near future, but for now, it is not a part of the library.

Currently, the library supports 2 modes:
1. One-time location fetch
2. Continuous location fetch (cannot be stopped unless the host activity is destroyed)

**Comment by mumayank** [comment]
@vevek Special thanks to you for helping others in the community so promptly!

@ifnyas I hope this would solve your query. I will leave the closing of this issue on you. Please revert back with comments in case you're still facing issues. Thanks :)

**Comment by irfnyas** [comment]
Ah I see, you know I think your library will be perfect if only it has `stopLocationUpdates()`...
Thanks for your response and looking forward to your updates. Your library has been really helpful to me, cheers

**Comment by vevek** [comment]
@mumayank No worries. Thanks for this awesome library 😀

**Comment by vevek** [comment]
@ifnyas In that case you can follow my first comment to get what you're looking for. 👍
