### ISSUE TITLE
the locations are in array list, which one do I have to use ?

### ISSUE THREAD

**Issue by AgungLaksana** [mumayank/AirLocation#17]
sorry this is actually not an issue, i am just confused.

from the onSuccess listener, we will get list of locations, what does it mean ? why list of locations instead of just one location ? and which one do I have to use ?

```
       override fun onSuccess(locations: ArrayList<Location>) {

        }
```

**Comment by mumayank** [comment]
Appreciate you asking this question. This will help others in case they are also having the same confusion.

In absolutely layman terms, the library gives you the device's location updates. Now, sometimes due to network or GPS or a lot of other issues, live location may not come in real-time. There may be some delay in delivering the locations. In such cases, to ensure you receive the entire track of the user's location, an array is sent instead of the latest value. The array's elements are ordered chronologically. If you're interested in the latest value only, please take the last item from the array.

I understand and agree with your point that ideally only the latest value should be served. But as you may have understood from the above reasoning, it is technologically not possible to do so all the time. If you consider a use case like that of a cab app (Uber), if the track is not served to the app, the car would appear flying from one place to another instead of honoring the road track.

Hope this helps :)
