### ISSUE TITLE
Add huawei location would be nice 

### ISSUE THREAD

**Issue by jehad-suliman** [mumayank/AirLocation#21]

**Comment by mumayank** [comment]
Due to the malpractices of data theft done by Huawei, countries like the USA and Australia have banned Huawei from their country. Google has its head office in the USA, and hence, must comply with the state's law. Since Google owns and runs the Android platform and its development, Google has banned Huawei devices. Huawei has released their own new OS for their devices. The only Huawei devices still running on Android are older devices - which will soon become outdated. So, support for Huawei will not be provided. I hope you understand. Thanks.
