### ISSUE TITLE
Location Not get Sometimes

### ISSUE THREAD

**Issue by Shubham178046** [mumayank/AirLocation#22]
i got this error HIGH_PRECISION_LOCATION_NA_TRY_AGAIN_PREFERABLY_WITH_NETWORK_CONNECTIVITY

**Comment by rik783** [comment]
I got the same error. But I don't no why he is giving the error

**Comment by mumayank** [comment]
Hi guys, the right use case of this library is when you require the most-precise real-time location of the device. Sometimes, it is not available due to no or low network connectivity. On flaky network, when exactly this happens is impossible to know. Thus, we need a fail case where the user should be informed that high-precision location could not be fetched. The user needs to try again, preferably with network connectivity. So, I made this error message antipattern but descriptive so that people understand it automatically.

**Comment by Shubham178046** [comment]
so can you tell me how can we resolve this issue

**Comment by Shubham178046** [comment]
how we can retry until the location does not get

**Comment by mumayank** [comment]
Finish the activity, and request the user to connect to a network and try again.

**Comment by Shubham178046** [comment]
so for this issue, you have set an exception message and code. can you share with me what's the message and code you have set for this issue because using message and code I will retry again if the user got this message and the code
