### ISSUE TITLE
Ethernet Location Problem

### ISSUE THREAD

**Issue by DatL4g** [mumayank/AirLocation#5]
I have an Android TV and there is a problem when connected via ethernet.

When the TV communicates with WiFi everything works as it should, but with LAN, he can not determine the location.

The library does not throw an error or return a location value.
(This is also the case with Google's FusedLocationProviderClient)

Maybe you could even see if it is possible with GPS or NetworkLocationProvider to retrieve the location otherwise it would be good if it would throw an error.

**Comment by mumayank** [comment]
Thank you for bringing this up. The mission statement of this library is to make it easy to use Google's location library. The library does not improve location accuracy or guarantee over and above what Google's location library would return. Since it is very complex to use Google's location library, hence I designed this to make that process seamless.

Having said that, I would look into it when time allows. Keeping it under enhancement till then.

**Comment by mumayank** [comment]
@DATL4G The lib has been updated to bring live location updates to the users. Given the current roadmap of the lib, and the ever-changing policies of Google/ Android, the focus is to improve the lib in a way so that usage of google's play services (location) is a breeze for an android developer. Hence, this issue is out of scope. Thank you for understanding.
