### ISSUE TITLE
Is this library working on background process

### ISSUE THREAD

**Issue by hafiz013** [mumayank/AirLocation#7]
Hi dear developer, is this library support for background process since from android 8 above google has make limited resource to get location.

**Comment by javierpe** [comment]
Any update for this? Im working with Schedulers and Workers. Thank you in advance!

**Comment by mumayank** [comment]
This library does not do anything new or different than what is already possible using Google's location APIs. What this library does is, however, to reduce all the hard work required to fetch the user's android mobile phone's current location.

If Google has limited resources to get the location in Android 8 and above, then that is the reality. Had you had fetched the location by following Google's official documentation for fetching the location, you would have arrived a the exact same result as this library would. (Because internally both are doing the exact same step!)

**Comment by peterslight** [comment]
hello thanks for this lib, but can I wrap this implementation in a service to fetch updates periodically?
